# Generated by Django 4.2.11 on 2025-02-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date released')),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date booked')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.movie')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.seat')),
            ],
        ),
    ]
